version: "3"
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    ports:
      - 8281:80
    volumes:
      - ./freshrss_data:/config
    restart: unless-stopped
