version: '3.8'

# SOCKS5 Proxy Server: Secure your web traffic.
# Connect your browser or apps to your server's IP on port 1080.

services:
  socks5:
    image: xkuma/socks5:latest
    container_name: socks5-server
    ports:
      - "1080:1080"
    environment:
      - USER=YOUR_USERNAME  # Change this!
      - PASS=YOUR_PASSWORD  # Change this!
    restart: unless-stopped
